### ISSUE TITLE
Empty object throws authencication error

### ISSUE THREAD

**Issue by amitava82** [azuqua/azuqua.js#18]
```
azuqua.invoke(alias, {}, true, done);
throws  "Authenticiy cannot be verified. Please check your headers"
```
Possibly hashing/decoding mismatch with api

**Comment by quy-le** [comment]
**Works for  me:**

```javascript
azuqua.invoke("551c70a9df440ef3e435b37a5e27ad97", {}, function () {
  console.log(arguments);
});
```

**Output**

```
Quys-MacBook-Pro:azuqua.js quyle$ node test.js
{ '0': null, '1': { data: { a: '' } } }
```

Check if your alias, key and secret are correct. I'm running against alpha.

**Comment by amitava82** [comment]
It works if I pass some random property instead of empty object. Testing
against alpha. I'll create some more repo case

**Comment by quy-le** [comment]
I reproduced the issue in prod. I'll take a look.

**Comment by quy-le** [comment]
@amitava82 Since it works it in alpha, let's just wait till those changes get pushed to PROD. Once it does get pushed, it'll be fixed (prod push this Friday).

**Comment by amitava82** [comment]
It is happening for me in alpha. Perhaps try creating a http flo without
any fields to repo.

**Comment by quy-le** [comment]
Thanks Amitava. Will try this.

**Comment by quy-le** [comment]
Hey @amitava82, it works in alpha. I created an HTTP with no inputs and returns no outputs as displayed below:

<img width="520" alt="screen shot 2015-10-20 at 11 48 28 am" src="https://cloud.githubusercontent.com/assets/11967684/10617696/abddbca4-7720-11e5-8c1a-19720b265cd3.png">

I can run the FLO successfully from the designer and client:

<img width="624" alt="screen shot 2015-10-20 at 11 50 38 am" src="https://cloud.githubusercontent.com/assets/11967684/10617731/d611e766-7720-11e5-866d-99fa7ee41f32.png">

**Client**

```javascript
var azuqua = new Azuqua(alpha_key, alpha_secret, {
    host: 'alphaapi.azuqua.com',
  });

//alpha
azuqua.invoke("0e5b29dfccce1330a90d5e6d2c524d97", {}, true, function () {
  console.log(arguments);
});
```

**Output**
```
Quys-MacBook-Pro:azuqua.js quyle$ node test.js 
params {}
{ '0': null, '1': { data: {} } }
```

Are you using the latest version of the client?

**Comment by kingozzy24** [comment]
This has been fixed, api was converting an empty object to an empty string when trying to do the hash validation.
