### ISSUE TITLE
Add utf-8 enconding to crypto hash

### ISSUE THREAD

**Issue by nikhilhasija** [azuqua/azuqua.js#6]
The use of binary encoding does not produce the right hash for extended characters

**Comment by quy-le** [comment]
I'll update the signData function to specify utf8 as the encoding when updating the hash:
```
crypto.createHmac("sha256", accessSecret).update(meta + data, 'utf8').digest("hex")
```
If we update it in the client to support extended characters, we'll need to update ALF & API to do the same ( lib/helpers/application.js ):
```
return crypto.createHmac("sha256", key).update(data).digest("hex") === hash;
```
From the crypto documentation for the update method:

[hash.update](https://nodejs.org/api/crypto.html#crypto_hash_update_data_input_encoding)

> Updates the hash content with the given data, the encoding of which is given in input_encoding and can be 'utf8', 'ascii' or 'binary'. If no encoding is provided and the input is a string an encoding of 'binary' is enforced. If data is a Buffer then input_encoding is ignored.

The `update` method defaults to binary. Does everyone agree? If so, I'll make the fix to both Alf, Api, and all clients if they are needed.

**Comment by quy-le** [comment]
[StackOverflow answer using a Buffer that specifies UTF8 encoding.](http://stackoverflow.com/questions/12195480/node-js-crypto-cannot-create-hmac-on-chars-with-accents)

**Comment by nikhilhasija** [comment]
Agree.
